brew "tmux"
brew "fzf"
brew "vim"
brew "mas"
brew "jq"
brew "ag"
brew "dog"
tap "thoughtbot/formulae"
brew "rcm"
brew "fish"
cask "visual-studio-code"
cask "docker"
cask "iterm2"
cask "figma"
cask "flycut"
cask "shiftit"
cask "notion"
cask "firefox"
mas "bear", id: 1091189122
mas "mr tidy", id: 1063178800
