#!/bin/bash
# Usage: ./vncssh hostname ssh_port remote_user
# e.g. ./vnchssh hjhart.com 22024 hjhart

host=$1
port=5900
ssh_port=$2
user=$3

localport=$((30000 + RANDOM % 20000))
ssh -o ExitOnForwardFailure=yes -fNL "$localport:localhost:$port" "$host" -l "$user" -p $ssh_port || exit
pid=$(lsof -t -i:$localport)
open -W vnc://$user@localhost:$localport
kill "$pid"
